[package]
name = "train_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
csv = "1.3.1"

[dev-dependencies]
approx = "0.5.1"
